# Generated by Django 5.0.13 on 2025-05-15 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Charsheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("basic_info", models.TextField(blank=True)),
                ("primary_stats", models.TextField(blank=True)),
                ("combat_stats", models.TextField(blank=True)),
                ("skills", models.TextField(blank=True)),
                ("special_abilities", models.TextField(blank=True)),
                ("inventory_main", models.TextField(blank=True)),
                ("inventory_extra", models.TextField(blank=True)),
                ("backstory", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.campaign",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
