# Generated by Django 5.0.13 on 2025-05-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheets", "0002_alter_charsheet_name_alter_charsheet_player"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charsheet",
            name="backstory",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="charsheet",
            name="basic_info",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="charsheet",
            name="combat_stats",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="charsheet",
            name="inventory_extra",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="charsheet",
            name="inventory_main",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="charsheet",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="charsheet",
            name="primary_stats",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="charsheet",
            name="skills",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="charsheet",
            name="special_abilities",
            field=models.TextField(blank=True),
        ),
    ]
