# Generated by Django 5.0.13 on 2025-05-15 17:04

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("system", models.CharField(max_length=50)),
                ("premise", models.TextField()),
                (
                    "key",
                    models.CharField(
                        default=accounts.models.generate_random_key,
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosted_campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="campaigns", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "blog_campaign",
            },
        ),
    ]
