# Generated by Django 5.0.13 on 2025-05-13 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Charsheet",
        ),
    ]
