# Generated by Django 5.0.13 on 2025-03-27 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Post",
        ),
    ]
