# Generated by Django 5.0.13 on 2025-05-11 14:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("system", models.CharField(max_length=50)),
                ("premise", models.TextField()),
                ("key", models.CharField(max_length=50)),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="campaigns", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
