# Generated by Django 5.0.13 on 2025-05-11 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_auto_20250511_1503"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="blog.campaign"
            ),
        ),
    ]
