# Generated by Django 5.0.13 on 2025-05-12 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_post_campaign"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="system",
        ),
    ]
