# Generated by Django 5.0.13 on 2025-05-13 09:26

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_campaign_host"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="key",
            field=models.CharField(
                default=blog.models.generate_random_key, max_length=50, unique=True
            ),
        ),
    ]
