# Generated by Django 5.0.13 on 2025-05-13 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_charsheet"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Charsheet",
        ),
    ]
